"""Storage protocol that every backend implements. Callers never see SQL."""
from __future__ import annotations

from datetime import date
from typing import Protocol

from novera.domain.counterparties import CSA, Counterparty, NettingSet
from novera.domain.limits import Limit
from novera.domain.organisation import Organisation
from novera.domain.snapshots import PortfolioSnapshot


class Repository(Protocol):
    def init_schema(self) -> None: ...

    # Reference data
    def save_organisation(self, org: Organisation) -> None: ...
    def load_organisation(self, firm_id: str) -> Organisation: ...
    def save_counterparties(self, items: list[Counterparty]) -> None: ...
    def load_counterparties(self) -> list[Counterparty]: ...
    def save_netting_sets(self, items: list[NettingSet], csas: list[CSA]) -> None: ...
    def load_netting_sets(self) -> tuple[list[NettingSet], list[CSA]]: ...
    def save_limits(self, items: list[Limit]) -> None: ...
    def load_limits(self, on: date | None = None) -> list[Limit]: ...

    # Portfolio snapshots
    def save_portfolio_snapshot(self, snapshot: PortfolioSnapshot) -> str: ...
    def load_portfolio_snapshot(self, snapshot_id: str) -> PortfolioSnapshot: ...
    def list_portfolio_snapshots(self) -> list[tuple[str, date, int]]: ...
