"""Storage protocol that every backend implements. Callers never see SQL."""

from __future__ import annotations

from datetime import date
from typing import Protocol

import pandas as pd

from novera.domain.breaches import Breach, BreachAction, LimitIncrease
from novera.domain.counterparties import CSA, Counterparty, NettingSet
from novera.domain.limits import Limit
from novera.domain.organisation import Organisation
from novera.domain.snapshots import PortfolioSnapshot
from novera.market_data.risk_factors import RiskFactor
from novera.market_data.snapshot import MarketSnapshot
from novera.workflows.runs import AuditEvent, RunRecord


class Repository(Protocol):
    def init_schema(self) -> None: ...

    # Reference data
    def save_organisation(self, org: Organisation) -> None: ...
    def load_organisation(self, firm_id: str) -> Organisation: ...
    def save_counterparties(self, items: list[Counterparty]) -> None: ...
    def load_counterparties(self) -> list[Counterparty]: ...
    def save_netting_sets(self, items: list[NettingSet], csas: list[CSA]) -> None: ...
    def load_netting_sets(self) -> tuple[list[NettingSet], list[CSA]]: ...
    def save_limits(self, items: list[Limit]) -> None: ...
    def load_limits(self, on: date | None = None) -> list[Limit]: ...

    # Portfolio snapshots
    def save_portfolio_snapshot(self, snapshot: PortfolioSnapshot) -> str: ...
    def load_portfolio_snapshot(self, snapshot_id: str) -> PortfolioSnapshot: ...
    def list_portfolio_snapshots(self) -> list[tuple[str, date, int]]: ...

    # Market data
    def save_risk_factors(self, items: list[RiskFactor]) -> None: ...
    def load_risk_factors(self) -> list[RiskFactor]: ...
    def save_market_history(self, history: pd.DataFrame) -> int: ...
    def load_market_history(
        self, factor_ids: list[str] | None = None, start: date | None = None, end: date | None = None
    ) -> pd.DataFrame: ...
    def save_market_snapshot(self, snapshot: MarketSnapshot) -> str: ...
    def load_market_snapshot(self, snapshot_id: str) -> MarketSnapshot: ...
    def list_market_snapshots(self) -> list[tuple[str, date, int]]: ...

    # Runs and results
    def save_run(self, run: RunRecord) -> None: ...
    def load_run(self, run_id: str) -> RunRecord: ...
    def list_runs(self, run_type: str | None = None, limit: int = 50) -> list[RunRecord]: ...
    def latest_run(self, run_type: str = "EOD", status: str = "COMPLETED") -> RunRecord | None: ...
    def save_run_frame(self, run_id: str, name: str, frame: pd.DataFrame) -> int: ...
    def load_run_frame(self, run_id: str, name: str) -> pd.DataFrame: ...
    def save_audit_events(self, events: list[AuditEvent]) -> None: ...
    def load_audit_events(self, subject: str | None = None, limit: int = 200) -> pd.DataFrame: ...

    # Breach workflow
    def save_breach(self, breach: Breach) -> None: ...
    def load_breach(self, breach_id: str) -> Breach: ...
    def load_breaches(self, open_only: bool = False, limit_id: str | None = None) -> list[Breach]: ...
    def save_breach_action(self, action: BreachAction) -> None: ...
    def load_breach_actions(self, breach_id: str) -> list[BreachAction]: ...
    def save_increase(self, inc: LimitIncrease) -> None: ...
    def load_increase(self, increase_id: str) -> LimitIncrease: ...
    def load_increases(
        self, status: str | None = None, limit_id: str | None = None
    ) -> list[LimitIncrease]: ...
    def load_portfolio_snapshot_before(self, on: date) -> PortfolioSnapshot | None: ...

    # Analyst
    def save_analyst_answer(self, d: dict) -> None: ...
    def load_analyst_answers(self, limit: int = 50, session_id: str | None = None) -> list[dict]: ...

    # Alerts
    def save_alert(self, d: dict) -> None: ...
    def load_alerts(
        self, limit: int = 200, status: str | None = None, severity: str | None = None
    ) -> list[dict]: ...

    # Scheduler
    def save_job(self, d: dict) -> None: ...
    def load_jobs(self, limit: int = 100) -> list[dict]: ...

    # Market data provenance
    def save_market_provenance(self, rows: list[dict]) -> None: ...
    def load_market_provenance(self) -> pd.DataFrame: ...
